# Define classes of images to be downloaded from flickr
# and set count of images to download for each class.

classes:
  - name: cat
    count: 20000
  - name: dog
    count: 10000
  - name: frog
    count: 10000
  - name: bird
    count: 10000
  - name: flower
    count: 5000
  - name: tree
    count: 5000
  - name: mushroom
    count: 5000
  - name: sportscar
    count: 10000
  - name: boat
    count: 10000
  - name: jumbojet
    count: 5000


train_test_split:
  seed: 42

  # proportional - select n% of images from each class
  # absolute - select n images from each class
  type: 'absolute'
  test_size: 500


subset:
  # smaller dataset that can be used when
  # GPU is unavailable

  seed: 42

  # Percentage of the full dataset
  percentage: 20